title: "Your Name"
description: "PhD Candidate in Economics, University of Padua"
theme: jekyll-theme-primer

header_pages:
  - about.md
  - research.md

author: Your Name
email: your.email@unipd.it
google_scholar: https://scholar.google.com/citations?user=XXXX
